### PR TITLE
Allow keyboard shortcuts and prompt for search engines.

### PR DESCRIPTION
**Pull request by githubms**
Also, changed from e.key to e.which (former wasn't working well for me in Safari.)

### CODE REVIEW

**Comment by crshd** [comment]
Dammit, now I know why you changed the keybinding for Google :disappointed:

**Comment by githubms** [comment]
Sorry about that. You can change that back I think. Hope the changes are useful. Thanks for the pull!

**Comment by crshd** [comment]
Oh, I didn't pull the index, just the JS. That's why I noticed the <kbd>g</kbd> is interfering with <kbd>sg</kbd>. But there's really nothing I can do about that, except for changing the binding.

**Comment by githubms** [comment]
I believe it should still work with g for google.  It allows multi char key bindings and clears keys pressed after couple seconds.  You just cannot have multi key binding which *starts* with g or some other single char that's already taken.

**Comment by crshd** [comment]
Nah, once you hit <kbd>g</kbd>, it goes to Google instead of opening the prompt.

**Pull request closed without merging**
